{"uid":"1af780e063bd2ef0","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1663018225550,"stop":1663018225575,"duration":25},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > token is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > token is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at Suite.eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:134:15)\n    at ./cypress/e2e/Service/postagem.spec.js (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:133:1)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:20:30)\n    at 0 (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:158:18)\n    at __webpack_require__ (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:20:30)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:84:18)\n    at eval (https://conexaoqa.herokuapp.com/__cypress/tests?p=cypress\\e2e\\Service\\postagem.spec.js:87:10)\n    at eval (<anonymous>)\nFrom previous event:\n    at runScriptsFromUrls (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:179922:136)\n    at Object.runScripts (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:179937:12)\n    at $Cypress.onSpecWindow (https://conexaoqa.herokuapp.com/__cypress/runner/cypress_runner.js:168145:76)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":31,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"37dfb24a50a327ad","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > token is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1663018032824,"stop":1663018032859,"duration":35}},{"uid":"2f5c9db979b81c4b","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.name.fullName is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661262396914,"stop":1661262396958,"duration":44}},{"uid":"679780fef54d95de","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.name.fullName is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661262357493,"stop":1661262357596,"duration":103}},{"uid":"b285e9c572c4ff3d","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.name is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661262123426,"stop":1661262123561,"duration":135}},{"uid":"46ba90dd4891b328","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261963343,"stop":1661261963412,"duration":69}},{"uid":"91a9155dacae66b3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261943797,"stop":1661261943849,"duration":52}},{"uid":"7ceeef5573fd4bdb","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261709414,"stop":1661261709455,"duration":41}},{"uid":"96c12a0cd749688b","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261615663,"stop":1661261615695,"duration":32}},{"uid":"8ae7bef4a6d2829d","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261605159,"stop":1661261605203,"duration":44}},{"uid":"cb90544ba27ea8d0","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261581776,"stop":1661261581809,"duration":33}},{"uid":"452ee59054407106","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261548884,"stop":1661261548910,"duration":26}},{"uid":"c1e3d1db7d51568a","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.phone.number is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661261532220,"stop":1661261532366,"duration":146}},{"uid":"2c0053c5b971593","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.visit()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661193767054,"stop":1661193767088,"duration":34}},{"uid":"b9d7ec82088e5e74","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.random is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131535112,"stop":1661131535169,"duration":57}},{"uid":"fd2380759bfa67a","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.random.random is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131487791,"stop":1661131487846,"duration":55}},{"uid":"a8ab3c3044d5c6b3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.random.text is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131461413,"stop":1661131461474,"duration":61}},{"uid":"eed11987c9cebeef","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.address.address is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131374156,"stop":1661131374209,"duration":53}},{"uid":"ff6f1bede51297bb","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.name.lastname is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131134536,"stop":1661131134592,"duration":56}},{"uid":"4a8fe358ce41da36","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.lastname is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131094857,"stop":1661131094901,"duration":44}},{"uid":"603ae14bdc33e53a","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.comerce is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661131005657,"stop":1661131005703,"duration":46}},{"uid":"4383aa323028f87e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.empresa is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661130993938,"stop":1661130993978,"duration":40}},{"uid":"98f5b5503c79d82c","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.company.empresa is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661130933646,"stop":1661130933687,"duration":41}},{"uid":"8b8702caccea74b9","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.commerce.commerce is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661130887524,"stop":1661130887570,"duration":46}},{"uid":"9b1ba0418704a659","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.commerce.empresa is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1661130832602,"stop":1661130832645,"duration":43}},{"uid":"a259c10784027eb3","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.senha is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660767036403,"stop":1660767036433,"duration":30}},{"uid":"eb772bc0fa9d747e","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.senha is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660767005184,"stop":1660767005219,"duration":35}},{"uid":"984bc23acd1953e8","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > faker.internet.senha is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660766969837,"stop":1660766969862,"duration":25}},{"uid":"9a8a3e1db07791bf","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot find module 'undefined'\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660661797280,"stop":1660661797294,"duration":14}},{"uid":"8218c28ebcd0f266","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > be is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660910774,"stop":1660660910794,"duration":20}},{"uid":"e9e50f96b5c1a30b","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > beforeE is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660896117,"stop":1660660896135,"duration":18}},{"uid":"5812f3e28c23d7","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > be is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1660660886623,"stop":1660660886643,"duration":20}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"1af780e063bd2ef0.json","parameterValues":[]}